// <auto-generated />
using System;
using MFFMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MFFMS.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191126143214_Add")]
    partial class Add
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("MFFMS.API.Models.ChiTietDonNhapHang", b =>
                {
                    b.Property<int>("MaDonNhapHang");

                    b.Property<int>("MaTSTB");

                    b.Property<string>("DVT");

                    b.Property<decimal>("DonGia");

                    b.Property<int>("SoLuong");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaDonNhapHang", "MaTSTB");

                    b.HasIndex("MaTSTB");

                    b.ToTable("DanhSachChiTietDonNhapHang");
                });

            modelBuilder.Entity("MFFMS.API.Models.ChiTietHDDV", b =>
                {
                    b.Property<int>("SoHDDV");

                    b.Property<int>("MaDichVu");

                    b.Property<int>("SoLuong");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("SoHDDV", "MaDichVu");

                    b.HasIndex("MaDichVu");

                    b.ToTable("DanhSachChiTietHDDV");
                });

            modelBuilder.Entity("MFFMS.API.Models.DichVu", b =>
                {
                    b.Property<int>("MaDichVu");

                    b.Property<string>("DVT");

                    b.Property<decimal>("DonGia");

                    b.Property<string>("GhiChu");

                    b.Property<string>("TenDichVu")
                        .IsRequired();

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaDichVu");

                    b.HasIndex("TenDichVu")
                        .IsUnique();

                    b.ToTable("DanhSachDichVu");
                });

            modelBuilder.Entity("MFFMS.API.Models.DonNhapHang", b =>
                {
                    b.Property<int>("MaDonNhapHang");

                    b.Property<int>("MaNhaCungCap");

                    b.Property<string>("MaNhanVien")
                        .IsRequired();

                    b.Property<DateTime>("NgayGiaoHang");

                    b.Property<string>("NoiNhanHang");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaDonNhapHang");

                    b.HasIndex("MaNhaCungCap");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("DanhSachDonNhapHang");
                });

            modelBuilder.Entity("MFFMS.API.Models.HoaDonDichVu", b =>
                {
                    b.Property<int>("SoHDDV");

                    b.Property<string>("GhiChu");

                    b.Property<int>("MaDichVu");

                    b.Property<string>("MaKhachHang")
                        .IsRequired();

                    b.Property<DateTime>("NgayLap");

                    b.Property<DateTime>("NgaySuDung");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("SoHDDV");

                    b.HasIndex("MaDichVu");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("DanhSachHoaDonDichVu");
                });

            modelBuilder.Entity("MFFMS.API.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKhachHang");

                    b.Property<string>("DiaChi");

                    b.Property<string>("GhiChu");

                    b.Property<string>("GioiTinh");

                    b.Property<string>("SoDienThoai");

                    b.Property<string>("TenKhachHang");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaKhachHang");

                    b.ToTable("DanhSachKhachHang");
                });

            modelBuilder.Entity("MFFMS.API.Models.NhaCungCap", b =>
                {
                    b.Property<int>("MaNhaCungCap");

                    b.Property<string>("DiaChi");

                    b.Property<string>("GhiChu");

                    b.Property<string>("SoDienThoai")
                        .IsRequired();

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired();

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaNhaCungCap");

                    b.HasIndex("SoDienThoai")
                        .IsUnique();

                    b.HasIndex("TenNhaCungCap")
                        .IsUnique();

                    b.ToTable("DanhSachNhaCungCap");
                });

            modelBuilder.Entity("MFFMS.API.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNhanVien");

                    b.Property<string>("ChucVu")
                        .IsRequired();

                    b.Property<string>("GhiChu");

                    b.Property<string>("GioiTinh");

                    b.Property<decimal>("Luong");

                    b.Property<DateTime>("NgaySinh");

                    b.Property<string>("SoCMND")
                        .IsRequired();

                    b.Property<string>("SoDienThoai")
                        .IsRequired();

                    b.Property<string>("TenNhanVien");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("SoCMND")
                        .IsUnique();

                    b.HasIndex("SoDienThoai")
                        .IsUnique();

                    b.ToTable("DanhSachNhanVien");
                });

            modelBuilder.Entity("MFFMS.API.Models.SanBong", b =>
                {
                    b.Property<int>("MaSanBong");

                    b.Property<string>("DienTich")
                        .IsRequired();

                    b.Property<string>("GhiChu");

                    b.Property<string>("TenSanBong")
                        .IsRequired();

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaSanBong");

                    b.HasIndex("TenSanBong")
                        .IsUnique();

                    b.ToTable("DanhSachSanBong");
                });

            modelBuilder.Entity("MFFMS.API.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DiaChi");

                    b.Property<string>("Email");

                    b.Property<string>("GioiTinh");

                    b.Property<byte[]>("Hash");

                    b.Property<string>("HoVaTen");

                    b.Property<DateTime>("NgaySinh");

                    b.Property<string>("PhanQuyen");

                    b.Property<string>("QueQuan");

                    b.Property<byte[]>("Salt");

                    b.Property<string>("SoDienThoai");

                    b.Property<string>("TenDangNhap");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaTaiKhoan");

                    b.ToTable("DanhSachTaiKhoan");
                });

            modelBuilder.Entity("MFFMS.API.Models.TaiSanThietBi", b =>
                {
                    b.Property<int>("MaTSTB");

                    b.Property<int>("MaNhaCungCap");

                    b.Property<string>("TenTSTB")
                        .IsRequired();

                    b.Property<string>("ThongTinBaoHanh");

                    b.Property<string>("TinhTrang");

                    b.HasKey("MaTSTB");

                    b.HasIndex("MaNhaCungCap");

                    b.HasIndex("TenTSTB")
                        .IsUnique();

                    b.ToTable("DanhSachTaiSanThietBi");
                });

            modelBuilder.Entity("MFFMS.API.Models.ChiTietDonNhapHang", b =>
                {
                    b.HasOne("MFFMS.API.Models.DonNhapHang", "DonNhapHang")
                        .WithMany("ChiTietDonNhapHang")
                        .HasForeignKey("MaDonNhapHang")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MFFMS.API.Models.TaiSanThietBi", "TaiSanThietBi")
                        .WithMany("ChiTietDonNhapHang")
                        .HasForeignKey("MaTSTB")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MFFMS.API.Models.ChiTietHDDV", b =>
                {
                    b.HasOne("MFFMS.API.Models.DichVu", "DichVu")
                        .WithMany("ChiTietHDDV")
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MFFMS.API.Models.HoaDonDichVu", "HoaDonDichVu")
                        .WithMany("ChiTietHDDV")
                        .HasForeignKey("SoHDDV")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MFFMS.API.Models.DonNhapHang", b =>
                {
                    b.HasOne("MFFMS.API.Models.NhaCungCap", "NhaCungCap")
                        .WithMany("DonNhapHang")
                        .HasForeignKey("MaNhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MFFMS.API.Models.NhanVien", "NhanVien")
                        .WithMany("DonNhapHang")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MFFMS.API.Models.HoaDonDichVu", b =>
                {
                    b.HasOne("MFFMS.API.Models.DichVu", "DichVu")
                        .WithMany("HoaDonDichVu")
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MFFMS.API.Models.KhachHang", "KhachHang")
                        .WithMany("HoaDonDichVu")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MFFMS.API.Models.TaiSanThietBi", b =>
                {
                    b.HasOne("MFFMS.API.Models.NhaCungCap", "NhaCungCap")
                        .WithMany("TaiSanThietBi")
                        .HasForeignKey("MaNhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
