// <auto-generated />
using System;
using MFFMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MFFMS.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("MFFMS.API.Models.CaiDat", b =>
                {
                    b.Property<string>("MaCaiDat")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DaXoa");

                    b.Property<string>("DiaChi");

                    b.Property<string>("DiaChiTrenPhieu");

                    b.Property<string>("Fax");

                    b.Property<string>("SoDienThoai");

                    b.Property<string>("TenSanBong");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaCaiDat");

                    b.ToTable("DanhSachCaiDat");
                });

            modelBuilder.Entity("MFFMS.API.Models.ChiTietDonNhapHang", b =>
                {
                    b.Property<string>("MaDonNhapHang")
                        .HasMaxLength(200);

                    b.Property<string>("MaTSTB")
                        .HasMaxLength(200);

                    b.Property<string>("DVT");

                    b.Property<int>("DaXoa");

                    b.Property<double>("DonGia");

                    b.Property<int>("SoLuong");

                    b.Property<double>("ThanhTien");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaDonNhapHang", "MaTSTB");

                    b.HasIndex("MaTSTB");

                    b.ToTable("DanhSachChiTietDonNhapHang");
                });

            modelBuilder.Entity("MFFMS.API.Models.ChiTietHDDV", b =>
                {
                    b.Property<string>("SoHDDV")
                        .HasMaxLength(200);

                    b.Property<string>("MaDichVu")
                        .HasMaxLength(200);

                    b.Property<int>("DaXoa");

                    b.Property<double>("DonGia");

                    b.Property<int>("SoLuong");

                    b.Property<double>("ThanhTien");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("SoHDDV", "MaDichVu");

                    b.HasIndex("MaDichVu");

                    b.ToTable("DanhSachChiTietHDDV");
                });

            modelBuilder.Entity("MFFMS.API.Models.ChiTietPhieuDatSan", b =>
                {
                    b.Property<int>("MaChiTietPDS")
                        .HasMaxLength(200);

                    b.Property<int>("DaXoa");

                    b.Property<string>("MaPhieuDatSan")
                        .IsRequired();

                    b.Property<string>("MaSanBong")
                        .IsRequired();

                    b.Property<DateTime>("NgayDat");

                    b.Property<double>("ThanhTien");

                    b.Property<double>("ThoiGianBatDau");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<double>("ThoiGianKetThuc");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<double>("TienCoc");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaChiTietPDS");

                    b.HasIndex("MaPhieuDatSan");

                    b.HasIndex("MaSanBong", "ThoiGianBatDau")
                        .IsUnique();

                    b.ToTable("DanhSachChiTietPhieuDatSan");
                });

            modelBuilder.Entity("MFFMS.API.Models.DichVu", b =>
                {
                    b.Property<string>("MaDichVu")
                        .HasMaxLength(200);

                    b.Property<string>("DVT");

                    b.Property<int>("DaXoa");

                    b.Property<double>("DonGia");

                    b.Property<string>("GhiChu");

                    b.Property<string>("TenDichVu")
                        .IsRequired();

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaDichVu");

                    b.HasIndex("TenDichVu")
                        .IsUnique();

                    b.ToTable("DanhSachDichVu");
                });

            modelBuilder.Entity("MFFMS.API.Models.DonNhapHang", b =>
                {
                    b.Property<string>("MaDonNhapHang")
                        .HasMaxLength(200);

                    b.Property<double>("DaThanhToan");

                    b.Property<int>("DaXoa");

                    b.Property<string>("GhiChu");

                    b.Property<string>("MaNhaCungCap")
                        .IsRequired();

                    b.Property<string>("MaNhanVien")
                        .IsRequired();

                    b.Property<DateTime>("NgayGiaoHang");

                    b.Property<double>("ThanhTien");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaDonNhapHang");

                    b.HasIndex("MaNhaCungCap");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("DanhSachDonNhapHang");
                });

            modelBuilder.Entity("MFFMS.API.Models.HoaDonDichVu", b =>
                {
                    b.Property<string>("SoHDDV")
                        .HasMaxLength(200);

                    b.Property<double>("DaThanhToan");

                    b.Property<int>("DaXoa");

                    b.Property<string>("DichVuMaDichVu");

                    b.Property<string>("GhiChu");

                    b.Property<string>("MaKhachHang")
                        .IsRequired();

                    b.Property<string>("MaNhanVien")
                        .IsRequired();

                    b.Property<DateTime>("NgayLap");

                    b.Property<DateTime>("NgaySuDung");

                    b.Property<double>("ThanhTien");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("SoHDDV");

                    b.HasIndex("DichVuMaDichVu");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("DanhSachHoaDonDichVu");
                });

            modelBuilder.Entity("MFFMS.API.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(200);

                    b.Property<int>("DaXoa");

                    b.Property<string>("DiaChi");

                    b.Property<string>("GhiChu");

                    b.Property<string>("GioiTinh");

                    b.Property<DateTime>("NgaySinh");

                    b.Property<string>("SoDienThoai");

                    b.Property<string>("TenKhachHang");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaKhachHang");

                    b.ToTable("DanhSachKhachHang");
                });

            modelBuilder.Entity("MFFMS.API.Models.NhaCungCap", b =>
                {
                    b.Property<string>("MaNhaCungCap")
                        .HasMaxLength(200);

                    b.Property<int>("DaXoa");

                    b.Property<string>("DiaChi");

                    b.Property<string>("GhiChu");

                    b.Property<string>("SoDienThoai")
                        .IsRequired();

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired();

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaNhaCungCap");

                    b.HasIndex("SoDienThoai")
                        .IsUnique();

                    b.HasIndex("TenNhaCungCap")
                        .IsUnique();

                    b.ToTable("DanhSachNhaCungCap");
                });

            modelBuilder.Entity("MFFMS.API.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(200);

                    b.Property<string>("ChucVu")
                        .IsRequired();

                    b.Property<int>("DaXoa");

                    b.Property<string>("DiaChi");

                    b.Property<string>("GhiChu");

                    b.Property<string>("GioiTinh");

                    b.Property<double>("Luong");

                    b.Property<DateTime>("NgaySinh");

                    b.Property<string>("SoCMND")
                        .IsRequired();

                    b.Property<string>("SoDienThoai")
                        .IsRequired();

                    b.Property<string>("TenNhanVien");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("SoCMND")
                        .IsUnique();

                    b.HasIndex("SoDienThoai")
                        .IsUnique();

                    b.ToTable("DanhSachNhanVien");
                });

            modelBuilder.Entity("MFFMS.API.Models.PhieuDatSan", b =>
                {
                    b.Property<string>("MaPhieuDatSan")
                        .HasMaxLength(200);

                    b.Property<int>("DaXoa");

                    b.Property<string>("MaKhachHang")
                        .IsRequired();

                    b.Property<string>("MaNhanVien")
                        .IsRequired();

                    b.Property<DateTime>("NgayLap");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<double>("TongTien");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaPhieuDatSan");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("DanhSachPhieuDatSan");
                });

            modelBuilder.Entity("MFFMS.API.Models.SanBong", b =>
                {
                    b.Property<string>("MaSanBong")
                        .HasMaxLength(200);

                    b.Property<double>("ChieuDai");

                    b.Property<double>("ChieuRong");

                    b.Property<int>("DaXoa");

                    b.Property<double>("DienTich");

                    b.Property<string>("GhiChu");

                    b.Property<string>("TenSanBong")
                        .IsRequired();

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaSanBong");

                    b.HasIndex("TenSanBong")
                        .IsUnique();

                    b.ToTable("DanhSachSanBong");
                });

            modelBuilder.Entity("MFFMS.API.Models.TaiKhoan", b =>
                {
                    b.Property<string>("MaTaiKhoan")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DaXoa");

                    b.Property<string>("DiaChi");

                    b.Property<string>("Email");

                    b.Property<string>("GioiTinh");

                    b.Property<byte[]>("Hash");

                    b.Property<string>("HoVaTen");

                    b.Property<DateTime>("NgaySinh");

                    b.Property<string>("PhanQuyen");

                    b.Property<byte[]>("Salt");

                    b.Property<string>("SoDienThoai");

                    b.Property<string>("TenDangNhap");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaTaiKhoan");

                    b.ToTable("DanhSachTaiKhoan");
                });

            modelBuilder.Entity("MFFMS.API.Models.TaiSanThietBi", b =>
                {
                    b.Property<string>("MaTSTB")
                        .HasMaxLength(200);

                    b.Property<int>("DaXoa");

                    b.Property<string>("MaNhaCungCap")
                        .IsRequired();

                    b.Property<string>("TenTSTB")
                        .IsRequired();

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<string>("ThongTinBaoHanh");

                    b.Property<string>("TinhTrang");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaTSTB");

                    b.HasIndex("MaNhaCungCap");

                    b.HasIndex("TenTSTB")
                        .IsUnique();

                    b.ToTable("DanhSachTaiSanThietBi");
                });

            modelBuilder.Entity("MFFMS.API.Models.ChiTietDonNhapHang", b =>
                {
                    b.HasOne("MFFMS.API.Models.DonNhapHang", "DonNhapHang")
                        .WithMany("ChiTietDonNhapHang")
                        .HasForeignKey("MaDonNhapHang")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MFFMS.API.Models.TaiSanThietBi", "TaiSanThietBi")
                        .WithMany("ChiTietDonNhapHang")
                        .HasForeignKey("MaTSTB")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MFFMS.API.Models.ChiTietHDDV", b =>
                {
                    b.HasOne("MFFMS.API.Models.DichVu", "DichVu")
                        .WithMany("ChiTietHDDV")
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MFFMS.API.Models.HoaDonDichVu", "HoaDonDichVu")
                        .WithMany("ChiTietHDDV")
                        .HasForeignKey("SoHDDV")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MFFMS.API.Models.ChiTietPhieuDatSan", b =>
                {
                    b.HasOne("MFFMS.API.Models.PhieuDatSan", "PhieuDatSan")
                        .WithMany("ChiTietPhieuDatSan")
                        .HasForeignKey("MaPhieuDatSan")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MFFMS.API.Models.SanBong", "SanBong")
                        .WithMany("ChiTietPhieuDatSan")
                        .HasForeignKey("MaSanBong")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MFFMS.API.Models.DonNhapHang", b =>
                {
                    b.HasOne("MFFMS.API.Models.NhaCungCap", "NhaCungCap")
                        .WithMany("DonNhapHang")
                        .HasForeignKey("MaNhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MFFMS.API.Models.NhanVien", "NhanVien")
                        .WithMany("DonNhapHang")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MFFMS.API.Models.HoaDonDichVu", b =>
                {
                    b.HasOne("MFFMS.API.Models.DichVu")
                        .WithMany("HoaDonDichVu")
                        .HasForeignKey("DichVuMaDichVu");

                    b.HasOne("MFFMS.API.Models.KhachHang", "KhachHang")
                        .WithMany("HoaDonDichVu")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MFFMS.API.Models.NhanVien", "NhanVien")
                        .WithMany("HoaDonDichVu")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MFFMS.API.Models.PhieuDatSan", b =>
                {
                    b.HasOne("MFFMS.API.Models.KhachHang", "KhachHang")
                        .WithMany("PhieuDatSan")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MFFMS.API.Models.NhanVien", "NhanVien")
                        .WithMany("PhieuDatSan")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MFFMS.API.Models.TaiSanThietBi", b =>
                {
                    b.HasOne("MFFMS.API.Models.NhaCungCap", "NhaCungCap")
                        .WithMany("TaiSanThietBi")
                        .HasForeignKey("MaNhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
